#!/bin/sh

msg=`cat $1`

msg=`echo "$msg" | sed 's/:tada:/🎉/'`
msg=`echo "$msg" | sed 's/:revert:/⏳/'`
msg=`echo "$msg" | sed 's/:build:/📦/'`
msg=`echo "$msg" | sed 's/:ci:/🤖/'`
msg=`echo "$msg" | sed 's/:docs:/📖/'`
msg=`echo "$msg" | sed 's/:feat:/🌟/'`
msg=`echo "$msg" | sed 's/:fix:/🚑/'`
msg=`echo "$msg" | sed 's/:perf:/⚡/'`
msg=`echo "$msg" | sed 's/:refactor:/🚧/'`
msg=`echo "$msg" | sed 's/:style:/💄/'`
msg=`echo "$msg" | sed 's/:test:/✅/'`

echo "$msg" > $1
